[package]
name = "Raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_approx_eq = "1.1.0"
crossbeam = "0.8.4"
image = "0.25.6"
jpeg-decoder = "0.3.2"
palette = "0.7.6"
rand = "0.9.2"
serde = "1.0.219"
serde_with = "3.14.0"
